kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ceph-rdb
provisioner: kubernetes.io/rdb
parameters:
  monitors: 172.187.10.221:6789
  adminId: admin
  adminSecretName: ceph-secret
  pool: rbd 
  userId: admin
  userSecretName: ceph-secret